---
title: "Loop"
output:
  pdf_document: default
  html_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs/") })
---

```{r setup, include=FALSE}
##DO NOT KNITR THIS FILE
#knitr options
knitr::opts_chunk$set(echo = TRUE)
#packages
library(readxl)
library(tidyverse)
library(rmarkdown)
```

```{r path}
path2localfile<-"../data/"
pathoutput<-"../docs/"
species = read_excel(paste0(path2localfile,"dataLOOP.xlsx"))
```

```{r read, warning=FALSE, echo=FALSE, message=FALSE, autodep=TRUE}
#generate pdf files in French
     for (i in 1:nrow(species)) {
      fichname<-paste0("Echelle_", species$spplat[i],"_", species$sex[i], ".pdf")
       render("ScaleFR.rmd", 
         params=list(spplat=species$spplat[i], sppeng=species$sppeng[i], sex=species$sex[i], sppfr=species$sppfr[i]),
         output_file=fichname)
       file.copy(fichname,to=paste0(pathoutput,fichname),overwrite=T)
      file.remove(fichname)
}
#generate pdf files in English
     for (i in 1:nrow(species)) {
      fichname<-paste0("Scale_", species$spplat[i],"_", species$sex[i], ".pdf")
       render("ScaleENG.rmd", 
         params=list(spplat=species$spplat[i], sppeng=species$sppeng[i], sex=species$sex[i], sppfr=species$sppfr[i]),
         output_file=fichname)
       file.copy(fichname,to=paste0(pathoutput,fichname),overwrite=T)
      file.remove(fichname)
}
```

