---
title: ' '
geometry: "left=1cm,right=1cm,top=0.5cm,bottom=0.5cm"
number_sections : no
pagestyle: "empty"
output:
  html_document: default
  word_document: default
  pdf_document: default
params:
  sppfr: "Bar"
---

```{r setup, include=FALSE}
#knit option
knitr::opts_chunk$set(echo = TRUE,fig.pos = 'h',dpi=32)
#packages
library(dplyr, warn.conflicts = FALSE)      # because tidyverse
library(readxl, warn.conflicts = FALSE)     # to read excel file
library(knitr, warn.conflicts = FALSE)      # to elaborate html/pdf
library(flextable, warn.conflicts = FALSE)  # to elaborate figures/tables
library(officer, warn.conflicts = FALSE)    # to customize tables
library(magick, warn.conflicts = FALSE)
library(tidyr)
library(gridExtra)

#creates a function to read image with their right dimensions
fratimg<-function(pathimg){
	imgdim<-image_info(image_read(pathimg))
	imgratio<- imgdim$height/imgdim$width
	return(imgratio)
}
#define variables
sppfr<-params$sppfr
```

```{r localpath, include=FALSE}
#define local path
path2localfile<-"../data/Photo_Guides/"
path2localfile2<-"../data/"
#define local images
#spp
imgspp<-paste0(path2localfile,"Image_Fish/",sppfr,".png")
#spp img ratio
imgsppratio<- fratimg(imgspp)
```

```{r referencetable, include=FALSE}
#load reference data
#build link for maturity phase photo data using the imgpath
Dataphoto <- read_excel(paste0(path2localfile2,"photo_guides.xlsx"),sheet=1)
DataFR <- read_excel(paste0(path2localfile2,"dataLOOP.xlsx"),sheet=1)
```

```{r borderstyle, echo=F, resultas='asis', warning=F, message=F,eval=T}
#to style table's borders
border1 = fp_border(color="black", width = 2)
border2 = fp_border(color="black", width = 1)
```
```{r GM, include=FALSE}
test61<-Dataphoto
test<- test61 %>% filter(Species=="Acanthostracion polygonius" | Species=="Acanthurus bahianus" | Species=="Aluterus scriptus" | Species=="Balistes vetula" | Species=="Calamus bajonado" | Species=="Cantherhines macrocerus" | Species=="Canthidermis sufflamen" | Species=="Caranx sp." | Species=="Epinephelinae sp." | Species=="Etelis oculatus" | Species=="Haemulon sp." | Species=="Lutjanus sp." | Species=="Mulloidichthys martinicus" | Species=="Ocyurus chrysurus" | Species=="Priacanthus arenatus" | Species=="Pseudupeneus maculatus" | Species=="Pterois volitans" | Species=="Sparisoma sp.")
colnames(test)[8]<-"ID"
test <- test %>%select(1,5,6,7,8)
test1<- test%>%filter(Guides=="yes" | ID =="E")
colnames(test1)[5]<-"ID"
test1<-test1%>%distinct(Species, Sex, ID, .keep_all=TRUE)
test1<-test1%>%select(2,3,4,5)
TEST<-test%>%select(2,3,4,5)
#return all rows that are not in commons between two tables
test8<-anti_join(TEST, test1, by = c("ID","Sex","Species"))
test9 <- pivot_wider(test8, names_from = Sex, values_from = ID)
test9$F<-as.character(test9$F)
test9$M<-as.character(test9$M)
test9$M<-gsub('c',"",as.character(test9$M))
test9$M<-gsub('["]',"",as.character(test9$M))
test9$M<-gsub('[(]',"",as.character(test9$M))
test9$M<-gsub('[)]',"",as.character(test9$M))
test9$F<-gsub('c',"",as.character(test9$F))
test9$F<-gsub('["]',"",as.character(test9$F))
test9$F<-gsub('[(]',"",as.character(test9$F))
test9$F<-gsub('[)]',"",as.character(test9$F))
sppfr<-DataFR
sppfr<-sppfr%>%filter(spplat=="Acanthostracion polygonius" | spplat=="Acanthurus bahianus" | spplat=="Aluterus scriptus" | spplat=="Balistes vetula" | spplat=="Calamus bajonado" | spplat=="Cantherhines macrocerus" | spplat=="Canthidermis sufflamen" | spplat=="Caranx sp." | spplat=="Epinephelinae sp." | spplat=="Etelis oculatus" | spplat=="Haemulon sp." | spplat=="Lutjanus sp." | spplat=="Mulloidichthys martinicus" | spplat=="Ocyurus chrysurus" | spplat=="Priacanthus arenatus" | spplat=="Pseudupeneus maculatus" | spplat=="Pterois volitans" | spplat=="Sparisoma sp.")
sppfr<-sppfr%>%select(1,2,3)
sppfr<-sppfr%>%distinct(spplat, sppeng, .keep_all=TRUE)
test10<-merge(test9, sppfr, all=TRUE)
test10<-test10%>%select(1,3,4,5,6)
test10<-test10[,c(5,1,4,2,3)]

imgspp<-paste0(path2localfile,"Image_Fish/",test10$sppfr,".png")
imgsppratio<- fratimg(imgspp)
```

```{r FRGM, echo=F, warning=F, message=F,fig.height=13.3,fig.width=6.8,out.width='500px', fig.align='center'}
test11<-data.frame(Photo=rep(imgspp,length(1)),Espèce=paste(test10$sppfr,test10$spplat,sep=" / "),Femelle=test10$F,Male=test10$M) %>% 
  separate(`Espèce`, c("french_name", "latin_name"), sep = "\\ / ") %>% 
  mutate(latin_name = paste0(" / ", latin_name) )

test13 <- flextable(test11, col_keys = c("Photo", "Espèce","Femelle","Male")) %>%
  compose(j = "Espèce", value =as_paragraph(french_name, as_i(latin_name)))%>%
	colformat_image(j="Photo",width=1,height=1*imgsppratio)%>%
	align(j=c("Photo","Espèce","Femelle","Male"), align = "center", part = "all")%>%
  bold(part = "header")%>%
  fontsize(size = 10, part = "body")%>%
  fontsize(size = 13, part = "header")%>%
  width(j = "Espèce", width = 1.8)%>%
  width(j = "Femelle", width = 1.3)%>%
  width(j = "Male", width = 1.3)%>%
  border_remove()%>%
  hline_top(part="header", border = border1 )%>%
  hline_bottom(part="header", border = border1 )%>%
  hline(part="body",border = border2)%>%
  set_header_labels(Espèce="Espèce")

plot(test13)
```
